### ISSUE TITLE
Guzzle require

### ISSUE THREAD

**Issue by trousers** [idimensionz/sendgrid-webapi-v3-php#1]
idimensionz/sendgrid-webapi-v3 dev-master requires guzzlehttp/guzzle 5.3.x-dev -> no matching package found.

**Comment by idimensionz** [comment]
Hi trousers, thanks for submitting the issue.  Probably has something to do with it be a -dev version.  I'll investigate.

**Comment by idimensionz** [comment]
Your composer.json probably has the default minimum stability of "stable".  Since the guzzle package ends in -dev, you need to change the minimum stability to dev.  This can be done by adding the 
`"minimum-stabilty": "dev",`
line to your project's composer.json file.

**Comment by trousers** [comment]
Thanks appreciate your help. I don't want to change the stability to dev but went with this for the time being

"minimum-stability": "dev",
"prefer-stable" : true,

Why not upgrade to Guzzle 6?

**Comment by idimensionz** [comment]
I use my own API and my production server does not have the version of PHP required by Guzzle 6.  So, I wouldn't be able to use that version myself.

However, I have designed my API client such that a different version of Guzzle could be substituted with little or no code changes (depending if there are any changes to the Guzzle API).  If you're a developer and want to give it a shot in a branch, I can explain the architecture for my API client so you can understand where any changes might be needed.

What features does Guzzle 6 offer that 5.3 does not?

**Comment by trousers** [comment]
Check the changelog for features and bugfixes

https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md

I'll have a look at making the changes

**Comment by idimensionz** [comment]
Thanks @trousers !  I've created a guzzle6 branch for those changes.  I'm going to close this issue but feel free to continue discussion about this repo in my HipChat chat room at https://www.hipchat.com/gFqa8nAS0
