### ISSUE TITLE
Incorrect fields checked in TemplateVersionDto->validateArray() when calling TemplateApi->getAllTemplates()

### ISSUE THREAD

**Issue by GloryFish** [idimensionz/sendgrid-webapi-v3-php#2]
I am implementing the iDimensionz SendGrid API and I believe I've encountered a bug in the implementation.

In `TemplateVersionDto->validateArray()` it is checking for the existence of 'html_content', 'plain_content', and 'subject'. However, according to the [SendGrid api reference](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html#-GET) those fields are not present when listing all templates. So, when calling `TemplateApi->getAllTemplates()` we get an error when it tries to instantiate a `TemplateVersionDto` from an array with partial data.

**Comment by idimensionz** [comment]
Hi! Thanks for reporting this issue here and in chat.  As I mentioned in our HipChat chat room Tuesday evening, I submitted a fix for this.  The fix was part of commit c27980181831f77ded84acb1f982ff5804996a23.  Please pull the latest version and let me know if you encounter any further issues.

**Comment by GloryFish** [comment]
Thank you very kindly. :)
